services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    labels:
      glance.name: Caddy
      glance.icon: di:caddy
      glance.description: reverse-proxy and automatic ssl
      glance.category: network
    volumes:
      - /home/m3v/shared/rpi-docker/data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/m3v/shared/rpi-docker/data/caddy/data:/data
      - /home/m3v/shared/rpi-docker/data/caddy/config:/config
      - /home/m3v/shared/rpi-docker/data/caddy/cloudflare-origin-cert/:/cloudflare-origin-cert
      - /mnt/m3vmain-web:/m3vmain-web
    ports:
      - 443:443
      - 2025:2025
    networks:
      - net
  
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    hostname: blocky
    labels:
      glance.name: blocky
      glance.icon: di:blocky
      glance.description: a dns proxy used for adblocking etc
      glance.category: network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/m3v/shared/rpi-docker/data/blocky/config-day.yml:/app/config.yml:ro
    networks:
      - net