services:
  # dockge:
  #   image: louislam/dockge:latest
  #   container_name: dockge
  #   restart: unless-stopped
  #   labels:
  #     glance.name: Dockge
  #     glance.icon: di:dockge
  #     glance.url: http://dockge.m3v.dev
  #     glance.description: docker gui management
  #     glance.category: management
  #   environment:
  #     - DOCKGE_STACKS_DIR=/home/m3v/shared/rpi-docker/compose
  #     - DOCKGE_ENABLE_CONSOLE=true
  #     - TZ=Europe/Amsterdam
  #   ports:
  #     - 5001:5001
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /home/m3v/shared/rpi-docker/compose:/home/m3v/shared/rpi-docker/compose
  #     - /home/m3v/shared/rpi-docker/data/dockge:/app/data
  #   networks:
  #     - net

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    labels:
      glance.name: Watchtower
      glance.icon: di:watchtower
      glance.description: automatic docker container updates
      glance.category: management   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    networks:
      - net

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    labels:
      glance.name: Uptime Kuma
      glance.icon: di:uptime-kuma
      glance.description: uptime tracking
      glance.category: management 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/m3v/shared/rpi-docker/compose:/home/m3v/shared/rpi-docker/compose
      - /home/m3v/shared/rpi-docker/data/uptime-kuma:/app/data
    ports:
      - 3001:3001
    networks:
      - net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /home/m3v/shared/rpi-docker/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - net

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
    network_mode: host

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - net

volumes:
  prometheus_data:
  grafana_data: