services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc
    restart: unless-stopped
    labels:
      glance.name: Minecraft
      glance.icon: si:minetest
      glance.description: Minecraft 1.21.8 server
      glance.tags: media
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.8"
      SERVER_PORT: "25565"
      INIT_MEMORY: 16G
      MAX_MEMORY: 32G
      ICON: "https://i.postimg.cc/t4h1jLMq/458e66e654804bceb89c3f7edb5adc49e21f93fav2-00-1.jpg"
      MOTD: "<white>the most sane 1.21.8 vanilla+ minecraft server\n<aqua>~~~~~~~~~~~~<『mc.m3v.dev』>~~~~~~~~~~~~"
      USE_AIKAR_FLAGS: "true"
      TZ: "Europe/Amsterdam"
      DIFFICULTY: "3"
      ENABLE_COMMAND_BLOCK: "true"
      SIMULATION_DISTANCE: "6"
      VIEW_DISTANCE: "12"
      SPAWN_PROTECTION: "1"
      OPS: |-
        m3v_
      ALLOW_FLIGHT: "true"
    volumes:
      - /home/m3v/srv/media/minecraft/nov-25-boys:/data
    network_mode: host



