include:
  - path: media/docker-compose.yml
  - path: images/docker-compose.yml
  - path: gaming/docker-compose.yml
  - path: management/docker-compose.yml

# network definition
networks:
  net:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
