services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    labels:
      glance.name: navidrome
      glance.icon: di:navidrome
      glance.description: a music streaming service
      glance.category: music
    environment:
      - ND_LOGLEVEL=info
      - ND_SCANSCHEDULE=1h
      - ND_LASTFM_APIKEY=${LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${LASTFM_SECRET}
      - ND_ENABLESHARING=true
      - ND_DEFAULTSHAREEXPIRATION=8760h
      - ND_BASEURL=https://navidrome.m3v.dev
      - ND_PORT=4533
    volumes:
      - /home/m3v/shared/rpi-docker/data/navidrome:/data
      - /home/m3v/shared/rpi-docker/media/music:/music:ro
    ports:
      - 4533:4533
    networks:
      - net
